services:
    # Core
    apy_grid.factory:
        public: true
        class: APY\DataGridBundle\Grid\GridFactory
        arguments:
            - '@apy_grid.registry'
            - '@request_stack'
            - '@router'
            - '@security.authorization_checker'
            - '@http_kernel'
            - '@twig'
    apy_grid.registry:
        public: true
        class: APY\DataGridBundle\Grid\GridRegistry

    # Types
    apy_grid.type.grid:
        class: APY\DataGridBundle\Grid\Type\GridType
        tags:
            - { name: apy_grid.type }

    # Columns
    apy_grid.column.text:
        class: APY\DataGridBundle\Grid\Column\TextColumn
        tags:
            - { name: apy_grid.column }
    apy_grid.column.array:
        class: APY\DataGridBundle\Grid\Column\ArrayColumn
        tags:
            - { name: apy_grid.column }
    apy_grid.column.blank:
        class: APY\DataGridBundle\Grid\Column\BlankColumn
        tags:
            - { name: apy_grid.column }
    apy_grid.column.boolean:
        class: APY\DataGridBundle\Grid\Column\BooleanColumn
        tags:
            - { name: apy_grid.column }
    apy_grid.column.date:
        class: APY\DataGridBundle\Grid\Column\DateColumn
        tags:
            - { name: apy_grid.column }
    apy_grid.column.date_time:
        class: APY\DataGridBundle\Grid\Column\DateTimeColumn
        tags:
            - { name: apy_grid.column }
    apy_grid.column.join:
        class: APY\DataGridBundle\Grid\Column\JoinColumn
        tags:
            - { name: apy_grid.column }
    apy_grid.column.number:
        class: APY\DataGridBundle\Grid\Column\NumberColumn
        tags:
            - { name: apy_grid.column }
    apy_grid.column.rank:
        class: APY\DataGridBundle\Grid\Column\RankColumn
        tags:
            - { name: apy_grid.column }
    apy_grid.column.time:
        class: APY\DataGridBundle\Grid\Column\TimeColumn
        tags:
            - { name: apy_grid.column }

    apy_grid.source_factory:
        public: true
        class: APY\DataGridBundle\Grid\SourceFactory
        arguments:
            - '@apy_grid.registry'

    apy_grid.source.vector:
        class: APY\DataGridBundle\Grid\Source\Vector
        tags:
            - { name: apy_grid.source, alias: vector }

    apy_grid.source.entity:
        class: APY\DataGridBundle\Grid\Source\Entity
        arguments:
            - '@doctrine'
            - '@grid.mapping.manager'
        tags:
            - { name: apy_grid.source, alias: entity }

    apy_grid.source.document:
        class: APY\DataGridBundle\Grid\Source\Document
        arguments:
            - '@doctrine_mongodb.odm.document_manager'
            - '@grid.mapping.manager'
        tags:
            - { name: apy_grid.source, alias: document }

    # exports
    apy_grid.export_factory:
        public: true
        class: APY\DataGridBundle\Grid\ExportFactory
        arguments:
            - '@apy_grid.registry'

    apy_grid.export.csv:
        public: true
        class: APY\DataGridBundle\Grid\Export\CSVExport
        arguments:
            - '@twig'
            - '@router'
            - '@translator'
            - '%kernel.charset%'
        tags:
            - { name: apy_grid.export, alias: csv }

    apy_grid.export.xml:
        public: true
        class: APY\DataGridBundle\Grid\Export\XMLExport
        arguments:
            - '@twig'
            - '@router'
            - '@translator'
            - '%kernel.charset%'
        tags:
            - { name: apy_grid.export, alias: xml }

    apy_grid.export.json:
        public: true
        class: APY\DataGridBundle\Grid\Export\JSONExport
        arguments:
            - '@twig'
            - '@router'
            - '@translator'
            - '%kernel.charset%'
        tags:
            - { name: apy_grid.export, alias: json }

    apy_grid.export.dsv:
        public: true
        class: APY\DataGridBundle\Grid\Export\DSVExport
        arguments:
            - '@twig'
            - '@router'
            - '@translator'
            - '%kernel.charset%'
        tags:
            - { name: apy_grid.export, alias: dsv }

    apy_grid.export.tsv:
        public: true
        class: APY\DataGridBundle\Grid\Export\TSVExport
        arguments:
            - '@twig'
            - '@router'
            - '@translator'
            - '%kernel.charset%'
        tags:
            - { name: apy_grid.export, alias: tsv }

    apy_grid.export.scsv:
        public: true
        class: APY\DataGridBundle\Grid\Export\SCSVExport
        arguments:
            - '@twig'
            - '@router'
            - '@translator'
            - '%kernel.charset%'
        tags:
            - { name: apy_grid.export, alias: scsv }

    apy_grid.export.excel:
        public: true
        class: APY\DataGridBundle\Grid\Export\ExcelExport
        arguments:
            - '@twig'
            - '@router'
            - '@translator'
            - '%kernel.charset%'
        tags:
            - { name: apy_grid.export, alias: excel }

    apy_grid.export.html:
        public: true
        class: APY\DataGridBundle\Grid\Export\HTMLExport
        arguments:
            - '@twig'
            - '@router'
            - '@translator'
            - '%kernel.charset%'
        tags:
            - { name: apy_grid.export, alias: html }
